version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=SocialNetworkingApplication.settings
      - MYSQL_DATABASE=social_network
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306  # MySQL default port
    depends_on:
      - db

  db:
    image: mysql:5.7  # Use MySQL 5.7 image (or specify another version)
    environment:
      MYSQL_DATABASE: social_network
      MYSQL_USER: root
      MYSQL_PASSWORD: riit
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql  # Mount volume to persist MySQL data

volumes:
  mysql_data:
